/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.AlunoController;
import controller.CursoAlunoController;
import controller.CursoController;
import controller.SituacaoCadastroController;
import java.awt.HeadlessException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Curso;
import model.CursoAluno;
import model.GerenciadorJanela;
import model.LookAndFeel;
import model.SituacaoCadastro;
import model.VRTableModel;


/**
 *
 * @author Matheus
 */
public class ConsultaCursoAlunoListGUI extends javax.swing.JInternalFrame {

    private CursoController cursoController = new CursoController();
    private AlunoController alunoController = new AlunoController();
    private SituacaoCadastroController SituacaoCadastroController = new SituacaoCadastroController();
    private CursoAlunoController cursoAlunoController = new CursoAlunoController();
    private CursoAluno cursoAlunoModel = new CursoAluno();
    private Aluno alunoModel = new Aluno();
    private Curso cursoModel = new Curso();
    private JDesktopPane desktop;
    private LookAndFeel tela = new LookAndFeel();
    GerenciadorJanela gerenciador = new GerenciadorJanela();
    CadastroCursoAlunoListGUI cadastro = new CadastroCursoAlunoListGUI();
    FiltroCursoAlunoGUI filtro = new FiltroCursoAlunoGUI();
    
    public ConsultaCursoAlunoListGUI(JDesktopPane desktop) {
        initComponents();
        this.desktop = desktop;
        tela.lookAndFeel(this, tela.VISUALJAVA);
        for (SituacaoCadastro situacaocadastro : SituacaoCadastroController.pesquisaSituacaoCadastro()) {
            cbSituacao.addItem(situacaocadastro);
            
        }
        cbSituacao.addItem("TODOS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        TextId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbSituacao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton4.setText("jButton4");

        setClosable(true);
        setMaximizable(true);
        setTitle("Consulta Curso Aluno");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Descrição");

        jLabel2.setText("Código");

        jLabel3.setText("Situação");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesquisa)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextId)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbSituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jButton6.setText("Sair");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton5)
                .addComponent(jButton6))
        );

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filtro.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filtro.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pesquisar();
    }//GEN-LAST:event_jButton1ActionPerformed

   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        gerenciador.GerenciadorJanela(cadastro, desktop);
        cadastro.TextClasse.setText("");
        cadastro.TextId.setText("");
        cadastro.cbCadastro.setSelectedIndex(0);
        cadastro.cbAluno.setSelectedIndex(0);
        cadastro.cbCurso.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Editar();
    }//GEN-LAST:event_jButton3ActionPerformed

    

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       gerenciador.GerenciadorJanela(filtro, desktop);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Pesquisar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
         if(evt.getClickCount() == 2){
         Editar();
     }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         gerenciador.GerenciadorJanela(filtro, desktop);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Excluir();
    }//GEN-LAST:event_jButton9ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextId;
    private javax.swing.JComboBox<Object> cbSituacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
     private void Pesquisar() throws HeadlessException {
        String descricao;
        Integer codigo;
        String pesquisa;
        String pesquisaAluno;
        String pesquisaCurso;
             
        if (TextId.getText().isEmpty() && txtPesquisa.getText().isEmpty() )  {
            JOptionPane.showMessageDialog(this, "Digite um campo para Consulta");
            descricao = null;

            pesquisa = null;
            pesquisaAluno = null;
            pesquisaCurso = null;
        }
        else{
            if(TextId.getText().isEmpty()){
            codigo = null;
            cursoAlunoModel.setCodigo(codigo);
            descricao = txtPesquisa.getText();
           
            if("TODOS".equals(cbSituacao.getSelectedItem())){
                cursoAlunoModel.setPesquisaSituacao("");
            }else{
                pesquisa = cbSituacao.getSelectedItem().toString();
                cursoAlunoModel.setPesquisaSituacao(pesquisa);
            }
            if("TODOS".equals(filtro.cbAluno.getSelectedItem())){
                 cursoAlunoModel.setPesquisaAluno("");
            }else{
                pesquisaAluno = filtro.cbAluno.getSelectedItem().toString();
                cursoAlunoModel.setPesquisaAluno(pesquisaAluno);
                filtro.cbAluno.setSelectedIndex(0);
                
            }
            if("TODOS".equals(filtro.cbCurso.getSelectedItem())){
                cursoAlunoModel.setPesquisaCurso("");
            }else{
                pesquisaCurso = filtro.cbCurso.getSelectedItem().toString();
                cursoAlunoModel.setPesquisaCurso(pesquisaCurso);
                filtro.cbCurso.setSelectedIndex(0);
                
            }  
            }else{
            codigo = Integer.parseInt(TextId.getText());
            cursoAlunoModel.setCodigo(codigo);
            descricao = txtPesquisa.getText();
           
            if("TODOS".equals(cbSituacao.getSelectedItem())){
                cursoAlunoModel.setPesquisaSituacao("");
            }else{
                pesquisa = cbSituacao.getSelectedItem().toString();
                cursoAlunoModel.setPesquisaSituacao(pesquisa);
            }
            if("TODOS".equals(filtro.cbAluno.getSelectedItem())){
                 cursoAlunoModel.setPesquisaAluno("");
            }else{
                pesquisaAluno = filtro.cbAluno.getSelectedItem().toString();
                cursoAlunoModel.setPesquisaAluno(pesquisaAluno);
                filtro.cbAluno.setSelectedIndex(0);
                
            }
            if("TODOS".equals(filtro.cbCurso.getSelectedItem())){
                cursoAlunoModel.setPesquisaCurso("");
            }else{
                pesquisaCurso = filtro.cbCurso.getSelectedItem().toString();
                cursoAlunoModel.setPesquisaCurso(pesquisaCurso);
                filtro.cbCurso.setSelectedIndex(0);
                
            }
            }
            
        }
        
        VRTableModel tableModel = new VRTableModel();
        tableModel.addColumn("Codigo");
        tableModel.addColumn("Codigo Aluno");
        tableModel.addColumn("Aluno");
        tableModel.addColumn("Codigo Curso");
        tableModel.addColumn("Curso");
        tableModel.addColumn("Classe");
        
        
        for(CursoAluno v : cursoAlunoController.listaCursoAluno(descricao, cursoAlunoModel)){
            tableModel.addRow(new Object[]{
                v.getCodigo(),
                v.getCodigo_aluno(),
                v.getNome_aluno(),
                v.getCodigo_curso(),
                v.getNome_curso(),
                v.getClasse()
                    
            });
        }
        
        tabela.setModel(tableModel);
        
        
    }
     private void Editar() throws NumberFormatException {
        int linha = tabela.getSelectedRow();
        if(linha >= 0){
            gerenciador.GerenciadorJanela(cadastro, desktop);
            String id = tabela.getValueAt(tabela.getSelectedRow(), 0).toString();
            cursoAlunoModel.setCodigo(Integer.parseInt(id));
            for(CursoAluno v : cursoAlunoController.pesquisaSituacao(cursoAlunoModel)){
                cadastro.TextId.setText(v.getCodigo().toString());
                cadastro.TextClasse.setText(v.getClasse());
                for (int i = 0; i < cadastro.cbCadastro.getItemCount(); i++) {
                    
                    if (((SituacaoCadastro) cadastro.cbCadastro.getItemAt(i)).getId() == v.getId_situacaocadastro()) {
                        cadastro.cbCadastro.setSelectedIndex(i);
                    }
                }
                for (int i = 0; i < cadastro.cbAluno.getItemCount(); i++) {
                    
                    if (((Aluno) cadastro.cbAluno.getItemAt(i)).getId() == v.getCodigo_aluno()) {
                        cadastro.cbAluno.setSelectedIndex(i);
                    }
                }
                for (int i = 0; i < cadastro.cbCurso.getItemCount(); i++) {
                    
                    if (((Curso) cadastro.cbCurso.getItemAt(i)).getCodigo() == v.getCodigo_curso()) {
                        cadastro.cbCurso.setSelectedIndex(i);
                    }
                }
            }
        }
    }
     private void Excluir() throws NumberFormatException, HeadlessException {
        String id = tabela.getValueAt(tabela.getSelectedRow(), 0).toString();
        cursoAlunoModel.setCodigo(Integer.parseInt(id));
        cursoAlunoController.deleteCursoAluno(cursoAlunoModel);
        JOptionPane.showMessageDialog(this, "Excluido com sucesso");
        Pesquisar();
    }

}
